language: python
cache:
  directories:
  - "$HOME/.cache/pip"
python:
  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "3.5-dev"
#  - "nightly" # currently points to 3.6-dev

# dependencies
install:
  - pip install coveralls
  - pip install -r requirements.txt

# command to run tests
script:
  - coverage run --source=sydres setup.py test

after_success:
  - coveralls
